jwt:
  expires-time: 7d

zap:
  level: info
  prefix: '[github.com/lxhcaicai/gin-vue-admin/server]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true
mysql:
  prefix: ""
  port: "30294"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  username: root
  password: "123456"
  path: 192.168.74.111
  engine: ""
  log-mode: error
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false
system:
  db-type: mysql
  router-prefix: ""
  addr: 7777
db-list:
  - type: ""
    alias-name: ""
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
    disable: true
captcha:
  key-long: 4
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600